# Generated by Django 5.0.3 on 2024-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='static/uploads/news/thumbnails')),
                ('short_heading', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('info_button_text', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/news')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
