# Generated by Django 5.0.3 on 2024-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.UUIDField(default='<function uuid4 at 0x000001A9D0E4DBC0>', editable=False, primary_key=True, serialize=False),
        ),
    ]
