# Generated by Django 5.0.3 on 2024-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.UUIDField(default='<function uuid4 at 0x000002039F5CDBC0>', primary_key=True, serialize=False),
        ),
    ]
