# Generated by Django 5.0.6 on 2024-07-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.UUIDField(default='<function uuid4 at 0x0000021649DA3560>', editable=False, primary_key=True, serialize=False),
        ),
    ]
