# Generated by Django 5.0.6 on 2024-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads/about-us/banners'),
        ),
    ]
