# Generated by Django 5.0.6 on 2024-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=400)),
                ('display_image', models.ImageField(upload_to='static/images')),
                ('content', models.TextField()),
                ('before_after_title', models.CharField(max_length=400)),
                ('before', models.ImageField(upload_to='static/images')),
                ('after', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
