# Generated by Django 5.0.6 on 2024-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('short_title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=400)),
                ('display_image', models.ImageField(upload_to='static/images')),
                ('content', models.TextField()),
                ('before_after_title', models.CharField(max_length=400)),
                ('before', models.ImageField(upload_to='static/images')),
                ('after', models.ImageField(upload_to='static/images')),
                ('service_page_slug', models.SlugField(editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
