# Generated by Django 5.0.6 on 2024-07-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
