# Generated by Django 5.0.6 on 2024-07-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='after',
        ),
        migrations.RemoveField(
            model_name='services',
            name='before',
        ),
        migrations.RemoveField(
            model_name='services',
            name='before_after_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='book_now_button_text',
        ),
        migrations.RemoveField(
            model_name='services',
            name='call_now_button_text',
        ),
        migrations.RemoveField(
            model_name='services',
            name='content',
        ),
        migrations.RemoveField(
            model_name='services',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='know_more_button',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_page_slug',
        ),
        migrations.RemoveField(
            model_name='services',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
        migrations.AddField(
            model_name='services',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
