# Generated by Django 5.0.6 on 2024-07-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_services_options_remove_services_after_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicePage',
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Service Page', 'verbose_name_plural': 'Service Page'},
        ),
    ]
