# Generated by Django 5.0.6 on 2024-07-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_detailedservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/services/banners')),
                ('heading', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.DeleteModel(
            name='DetailedService',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
