# Generated by Django 5.0.6 on 2024-07-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_banner_delete_detailedservice_delete_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Post Banner Content',
                'verbose_name_plural': 'Post Banner Content',
            },
        ),
    ]
