# Generated by Django 5.0.6 on 2024-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_postbannercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_heading', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('info_button_text', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='static/uploads/services/thumbnails')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('book_now_button_text', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/services')),
                ('before_after_heading', models.CharField(blank=True, max_length=300)),
                ('before_image', models.ImageField(blank=True, upload_to='static/uploads/services/before-after/before')),
                ('after_image', models.ImageField(blank=True, upload_to='static/uploads/services/before-after/after')),
            ],
        ),
    ]
