# Generated by Django 5.0.6 on 2024-07-30 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AddField(
            model_name='services',
            name='service_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
