# Generated by Django 5.0.6 on 2024-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_alter_services_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_id',
            field=models.UUIDField(default='<function uuid4 at 0x000002450AE83560>', editable=False, primary_key=True, serialize=False),
        ),
    ]
