# Generated by Django 5.0.6 on 2024-07-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerSlider',
        ),
    ]
