# Generated by Django 5.0.6 on 2024-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_bannerslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/uploads/banners')),
                ('heading', models.CharField(max_length=40)),
                ('sub_heading', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=250)),
            ],
        ),
    ]
