# Generated by Django 5.0.6 on 2024-07-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_banner_button_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='discription',
            new_name='description',
        ),
    ]
