# Generated by Django 5.0.6 on 2024-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_discription_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
