# Generated by Django 5.0.6 on 2024-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_banner_button_text_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_heading',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
