# Generated by Django 5.0.6 on 2024-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_banner_button_text_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads/banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
