# Generated by Django 5.0.3 on 2024-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_banner_button_text_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=40)),
                ('sub_heading', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
