# Generated by Django 5.0.3 on 2024-07-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(blank=True, upload_to='static/uploads/services/icons')),
                ('heading', models.CharField(blank=True, max_length=40)),
                ('service_image', models.ImageField(blank=True, upload_to='static/uploads/services')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
    ]
