# Generated by Django 5.0.3 on 2024-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_aboutservices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutservices',
            name='service_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
