# Generated by Django 5.0.3 on 2024-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
