# Generated by Django 5.0.3 on 2024-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_whyus_sub_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=40)),
                ('sub_heading', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Main Services',
                'verbose_name_plural': 'Main Services',
            },
        ),
        migrations.DeleteModel(
            name='WhyUs',
        ),
    ]
