# Generated by Django 5.0.6 on 2024-07-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_mainservices_delete_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('sub_heading', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/why-us')),
                ('image_text', models.CharField(blank=True, max_length=100)),
                ('mission_heading', models.CharField(blank=True, max_length=40)),
                ('mission_text', models.CharField(blank=True, max_length=250)),
                ('vision_heading', models.CharField(blank=True, max_length=40)),
                ('vision_text', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Why Us',
                'verbose_name_plural': 'Why Us',
            },
        ),
        migrations.DeleteModel(
            name='MainServices',
        ),
    ]
