# Generated by Django 5.0.6 on 2024-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_whyus_delete_mainservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
