# Generated by Django 5.0.6 on 2024-07-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_whyus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('sub_heading', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('service_1_title', models.CharField(blank=True, max_length=100)),
                ('service_1_image', models.ImageField(blank=True, upload_to='static/uploads/main-services')),
                ('service_2_title', models.CharField(blank=True, max_length=100)),
                ('service_2_image', models.ImageField(blank=True, upload_to='static/uploads/main-services')),
                ('service_3_title', models.CharField(blank=True, max_length=100)),
                ('service_3_image', models.ImageField(blank=True, upload_to='static/uploads/main-services')),
                ('button_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Main Services',
                'verbose_name_plural': 'Main Services',
            },
        ),
    ]
