# Generated by Django 5.0.6 on 2024-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_mainservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('sub_heading', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/specialized-in')),
            ],
            options={
                'verbose_name': 'Specialized In',
                'verbose_name_plural': 'Specialized In',
            },
        ),
    ]
