# Generated by Django 5.0.6 on 2024-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_specializedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedin',
            name='description_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='specializedin',
            name='heading_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='specializedin',
            name='sub_heading_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
