# Generated by Django 5.0.6 on 2024-07-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_specializedin_description_2_specializedin_heading_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specializedin',
            old_name='description_2',
            new_name='subsection_heading',
        ),
    ]
