# Generated by Django 5.0.6 on 2024-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_description_2_specializedin_subsection_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedInServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Specialized In Services',
                'verbose_name_plural': 'Specialized In Services',
            },
        ),
    ]
