# Generated by Django 5.0.6 on 2024-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Project Section Title',
                'verbose_name_plural': 'Project Section Title',
            },
        ),
    ]
