# Generated by Django 5.0.6 on 2024-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_projectsectiontitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('sub_heading', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Testimonial Section',
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
    ]
