# Generated by Django 5.0.6 on 2024-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_testimonialsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(blank=True, max_length=150)),
                ('review', models.CharField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
    ]
