# Generated by Django 5.0.6 on 2024-07-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='auther',
            new_name='author',
        ),
    ]
