# Generated by Django 5.0.6 on 2024-07-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='link_item_1',
            new_name='item_1_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='title_1',
            new_name='item_1_title',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='link_item_2',
            new_name='item_2_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='link_item_3',
            new_name='item_2_title',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='link_item_4',
            new_name='item_3_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='link_item_5',
            new_name='item_3_title',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='title_2',
            new_name='item_4_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='title_3',
            new_name='item_4_title',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='title_4',
            new_name='item_5_link',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='title_5',
            new_name='item_5_title',
        ),
    ]
