# Generated by Django 5.0.6 on 2024-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_rename_link_item_1_navbar_item_1_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
    ]
